import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { Download, FileSpreadsheet, IndianRupee, Package, ShoppingCart } from "lucide-react";
import { api } from "@/lib/api";
import { Empty, ErrorState, Loading, Panel, PageHeader, Stat, fmtBytes, fmtTime, inr } from "@/components/ops/ui";

const NAME = "nightly_sales_report.csv";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Reports — AWS Nightly Reports" },
      { name: "description", content: "Preview and download nightly_sales_report.csv generated by the Fargate task." },
      { property: "og:title", content: "Reports — AWS Nightly Reports" },
      { property: "og:description", content: "Preview and download the nightly sales report." },
    ],
  }),
  component: Reports,
});

function Reports() {
  const q = useQuery({ queryKey: ["report", NAME], queryFn: () => api.getReport(NAME) });
  const dl = useMutation({
    mutationFn: () => api.downloadReport(NAME),
    onSuccess: (blob) => {
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = NAME;
      a.click();
      URL.revokeObjectURL(url);
      toast.success("Download started");
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : "Download failed"),
  });
  if (q.isLoading) return <Loading />;
  if (q.error || !q.data) return <ErrorState error={q.error} onRetry={() => q.refetch()} />;
  const r = q.data;
  const rev = r.rows.reduce((a, x) => a + x.totalRevenue, 0);
  const qty = r.rows.reduce((a, x) => a + x.totalQuantity, 0);
  const orders = r.rows.reduce((a, x) => a + x.orderCount, 0);
  const top = [...r.rows].sort((a, b) => b.totalRevenue - a.totalRevenue)[0];

  return (
    <>
      <PageHeader title="Reports" desc={`s3://${r.bucket}/${r.key}`} actions={<button onClick={() => dl.mutate()} disabled={dl.isPending} className="flex items-center gap-2 rounded bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50"><Download className="h-4 w-4" /> Download CSV</button>} />
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <Stat label="Total revenue" icon={<IndianRupee className="h-4 w-4" />} value={inr(rev)} />
        <Stat label="Units sold" icon={<Package className="h-4 w-4" />} value={qty} />
        <Stat label="Orders" icon={<ShoppingCart className="h-4 w-4" />} value={orders} />
        <Stat label="Top product" icon={<FileSpreadsheet className="h-4 w-4" />} value={top?.product ?? "—"} sub={top ? inr(top.totalRevenue) : ""} />
      </div>
      <Panel title={<span className="font-mono">{r.name}</span>} className="mt-4" action={<span className="font-mono text-xs text-muted-foreground">{fmtBytes(r.sizeBytes)} · {fmtTime(r.lastModified)}</span>}>
        {r.rows.length === 0 ? <Empty label="Report is empty" /> : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="text-left text-xs text-muted-foreground"><tr><th className="py-2">Product</th><th className="text-right">Total quantity</th><th className="text-right">Total revenue</th><th className="text-right">Orders</th><th className="hidden w-1/4 pl-6 md:table-cell">Share</th></tr></thead>
              <tbody>
                {r.rows.map((x) => (
                  <tr key={x.product} className="border-t border-border">
                    <td className="py-2">{x.product}</td>
                    <td className="text-right font-mono">{x.totalQuantity}</td>
                    <td className="text-right font-mono">{inr(x.totalRevenue)}</td>
                    <td className="text-right font-mono">{x.orderCount}</td>
                    <td className="hidden pl-6 md:table-cell"><div className="h-1.5 rounded bg-muted"><div className="h-1.5 rounded bg-primary" style={{ width: `${(x.totalRevenue / rev) * 100}%` }} /></div></td>
                  </tr>
                ))}
                <tr className="border-t-2 border-border font-semibold"><td className="py-2">Total</td><td className="text-right font-mono">{qty}</td><td className="text-right font-mono">{inr(rev)}</td><td className="text-right font-mono">{orders}</td><td className="hidden md:table-cell" /></tr>
              </tbody>
            </table>
          </div>
        )}
      </Panel>
    </>
  );
}
