/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataRouteImport } from './routes/data'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RunRouteImport } from './routes/run'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ExecutionsIndexRouteImport } from './routes/executions.index'
import { Route as ExecutionsTaskIdRouteImport } from './routes/executions.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsIndexRoute = ExecutionsIndexRouteImport.update({
  id: '/executions/',
  path: '/executions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsTaskIdRoute = ExecutionsTaskIdRouteImport.update({
  id: '/executions/$taskId',
  path: '/executions/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/logs': typeof LogsRoute
  '/reports': typeof ReportsRoute
  '/run': typeof RunRoute
  '/scheduler': typeof SchedulerRoute
  '/status': typeof StatusRoute
  '/executions/$taskId': typeof ExecutionsTaskIdRoute
  '/executions/': typeof ExecutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/logs': typeof LogsRoute
  '/reports': typeof ReportsRoute
  '/run': typeof RunRoute
  '/scheduler': typeof SchedulerRoute
  '/status': typeof StatusRoute
  '/executions/$taskId': typeof ExecutionsTaskIdRoute
  '/executions': typeof ExecutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/logs': typeof LogsRoute
  '/reports': typeof ReportsRoute
  '/run': typeof RunRoute
  '/scheduler': typeof SchedulerRoute
  '/status': typeof StatusRoute
  '/executions/$taskId': typeof ExecutionsTaskIdRoute
  '/executions/': typeof ExecutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/logs'
    | '/reports'
    | '/run'
    | '/scheduler'
    | '/status'
    | '/executions/$taskId'
    | '/executions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/logs'
    | '/reports'
    | '/run'
    | '/scheduler'
    | '/status'
    | '/executions/$taskId'
    | '/executions'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/logs'
    | '/reports'
    | '/run'
    | '/scheduler'
    | '/status'
    | '/executions/$taskId'
    | '/executions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  LogsRoute: typeof LogsRoute
  ReportsRoute: typeof ReportsRoute
  RunRoute: typeof RunRoute
  SchedulerRoute: typeof SchedulerRoute
  StatusRoute: typeof StatusRoute
  ExecutionsTaskIdRoute: typeof ExecutionsTaskIdRoute
  ExecutionsIndexRoute: typeof ExecutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/': {
      id: '/executions/'
      path: '/executions'
      fullPath: '/executions/'
      preLoaderRoute: typeof ExecutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/$taskId': {
      id: '/executions/$taskId'
      path: '/executions/$taskId'
      fullPath: '/executions/$taskId'
      preLoaderRoute: typeof ExecutionsTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  LogsRoute: LogsRoute,
  ReportsRoute: ReportsRoute,
  RunRoute: RunRoute,
  SchedulerRoute: SchedulerRoute,
  StatusRoute: StatusRoute,
  ExecutionsTaskIdRoute: ExecutionsTaskIdRoute,
  ExecutionsIndexRoute: ExecutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
